language: java
java:
  - 1.8

install:
  - mvn clean install
  - mvn cobertura:cobertura

notifications:
email:
recipients:
- leonardocm92@hotmail.com
on_success: always
on_failure: always

after_success:
- bash <(curl -s https://codecov.io/bash)
